import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from "@/Context/Context";
import NavBar from "@/components/common/navbar/NavBar";
import Footer from "@/components/common/footer/Footer";
import ScrollToTop from "@/components/common/scrollToTop/ScrollToTop";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prathamesh Nimje",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MyContextProvider>
          <div data-theme={"light"} className="relative">
            <NavBar />
          </div>
          {children}
          <div className="bg-[#2A374A]">
            <Footer />
          </div>
          <ScrollToTop />
        </MyContextProvider>
      </body>
    </html>
  );
}
