[build]
  base = "frontend"
  command = "npm run build -- --debug"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Environment variables
[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_BACKEND_URL = "https://portfolio-backend-delta-two.vercel.app"